### ISSUE TITLE
Standardize your data before PCA 

### ISSUE THREAD

**Issue by armgilles** [sdimi/spotifav#1]
hey @sdimi I really like your post medium and read it with pleasure.

I check your notebook and I think you should normalize your data before doing some PCA using `StandardScaler`

Just my 2 cents :)

**Comment by sdimi** [comment]
hey @armgilles, thank you. Since the  data are already scaled to 0-100, I don't see why they should be scaled again. But yeah removing the mean and scaling to unit variance maybe give better PCA results. I'll test it!
